version: "3.4"
services:
  webserver:
    build: .
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus:v2.9.2
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:6.1.6
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards


